### ISSUE TITLE
DYMOLabel error

### ISSUE THREAD

**Issue by duggan1972** [autopkg/joshua-d-miller-recipes#100]
I'm getting an error in autopkg:
Error in local.munki.DYMOLabel: Processor: URLDownloader: Error: curl failure: The requested URL returned error: 403  (exit code 22)

Would this be an issue with the recipe?

Thank you.

**Comment by porkcube** [comment]
Seeing the same, running `curl https://download.dymo.com/dymo/Software/DLS8Setup.dmg` it appears they put it behind a Captcha 8/

**Comment by joshua-d-miller** [comment]
Ugh....I'm sorry to hear this. I'll be sure to contact them to hopefully address that

**Comment by duggan1972** [comment]
I updated the Trust for DYMOLabel, found the changes, and applied them. However I'm still getting an error in autopkg. It's the same error as before.

**Comment by joshua-d-miller** [comment]
Please try the latest change as the link needed to be updated. I know it's only HTTP but they have assured me it works and I have tested it. I have also asked DYMO to make us an HTTPS link

**Comment by duggan1972** [comment]
That may have worked. I updated trust for that recipe, and it seemed to have run normally. I'll check to see if it created the pkg  on the next run.

**Comment by porkcube** [comment]
Fixed for me, thanks!!

**Comment by joshua-d-miller** [comment]
Perfect! Glad to hear it's working again until they change the URL on me again! Thanks for verifying!
