### ISSUE TITLE
silhouettestudio .download is failing

### ISSUE THREAD

**Issue by macmule** [autopkg/joshua-d-miller-recipes#102]
fyi.. looks all .js now.. tried a few things but failed to resolve

```
URLTextSearcher
{'Input': {'re_pattern': 'href="\\/\\/(dl\\.silhcdn\\.com\\/\\S*)">Mac '
                         '\\(64-bit\\)',
           'result_output_var_name': 'match',
           'url': 'https://www.silhouetteamerica.com/software'}}
No match found on URL: https://www.silhouetteamerica.com/software
Failed.
Receipt written to /Users/ben/Library/AutoPkg/Cache/com.github.joshua-d-miller.autopkg.munki.silhouettestudio/receipts/com.github.joshua-d-miller.autopkg.munki-receipt-20210803-141226.plist

The following recipes failed:
    com.github.joshua-d-miller.autopkg.munki.silhouettestudio
        Error in com.github.joshua-d-miller.autopkg.munki.silhouettestudio: Processor: URLTextSearcher: Error: No match found on URL: https://www.silhouetteamerica.com/software
```

**Comment by joshua-d-miller** [comment]
I have contacted Silhouette requesting a direct download link. Hopefully I get a response.

**Comment by joshua-d-miller** [comment]
Unfortunately the company has basically told us we are on our own however I have gone ahead and sent another email to basically pester them into giving us a download URL. I would link to the URL for the latest version but it's a CDN randomly generated link which I believe will change each time a new version is released. If I get more information I'll be sure to let you know.

**Comment by ahousseini** [comment]
I wrote this processor if you are interested: https://github.com/autopkg/ahousseini-recipes/commit/ca2d73506b090dd48f67096b870ee0dd668208e0

**Comment by joshua-d-miller** [comment]
This has been switched to @ahousseini's URL Provider and will now function as intended. Thank you @ahousseini for creating the URL Provider.
