### ISSUE TITLE
Can't get Logitech Options / LogiMgr Installer 9.20.265

### ISSUE THREAD

**Issue by jw-macworks** [autopkg/joshua-d-miller-recipes#103]
I can't seem to get the current version, the recipe downloads Logitech Options-8.54.147

**Comment by joshua-d-miller** [comment]
I have updated the recipe with a direct download URL as it no longer requires searching. I have also tested the recipe and have had success. Please give it a try and let me know if it works for you.

**Comment by jw-macworks** [comment]
It works again. Thank you!
