### ISSUE TITLE
Missing <

### ISSUE THREAD

**Issue by rustymyers** [autopkg/joshua-d-miller-recipes#104]
You're probably already aware:

WARNING: plist error for /Users/sysman/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes/Dropbox/DropboxCapture.download.recipe: unexpected key at line 7
WARNING: plist error for /Users/sysman/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes/Dropbox/DropboxCapture.pkg.recipe: unexpected key at line 9

https://github.com/autopkg/joshua-d-miller-recipes/commit/35a9713ed394725029023174264b251005a8cd20#r58098848

**Comment by joshua-d-miller** [comment]
This has been corrected. Thank you for brining it to my attention.
