### ISSUE TITLE
Receipt issue on macOS Monterey with Box munki recipe

### ISSUE THREAD

**Issue by tristanthomas** [autopkg/joshua-d-miller-recipes#107]
If Box drive is installed for the first time on a device running macOS 12.0.1, only the three package receipts will be installed:
```
com.box.desktop.installer.local.appsupport
com.box.desktop.installer.autoupdater
com.box.desktop.installer.desktop
```

However, `MunkiImporter` adds the three package receipts above in addition to the receipt `com.box.desktop.installer.osxfuse` to the `receipts` array. This causes munki to get stuck in a reinstall loop for the Box package.

We can possibly fix this issue by setting `com.box.desktop.installer.osxfuse` as an optional receipt. We can maybe append the [MunkiPkginfoReceiptsEditor](https://github.com/autopkg/keeleysam-recipes/blob/master/GoogleTalkPlugin/MunkiPkginfoReceiptsEditor.py) processor to the Box munki recipe to make this change:
```
        <dict>
            <key>Arguments</key>
            <dict>
                <key>pkg_ids_set_optional_true</key>
                <array>
                    <string>com.box.desktop.installer.osxfuse</string>
                </array>
            </dict>
            <key>Processor</key>
            <string>com.github.keeleysam.recipes.GoogleTalkPlugin/MunkiPkginfoReceiptsEditor</string>
        </dict>
```

**Comment by joshua-d-miller** [comment]
So Sam's Optional Receipts is Python 2 but this was incorporated into Python 3 and I have gone ahead and implemented it. You should be all set now.

**Comment by pieterbowman** [comment]
The box.munki.recipe change now causes this warning:
WARNING: processor path not found for processor: MunkiOptionalReceiptEditor

The problem is that the path to the processor from keeleysam's recipes is missing.
