### ISSUE TITLE
Error in mendeleyreferencemanager.munki

### ISSUE THREAD

**Issue by Peter-Erik** [autopkg/joshua-d-miller-recipes#108]
Hi mendeleyreferencemanager.munki gives an error at this time:

autopkg run mendeleyreferencemanager.munki

Processing mendeleyreferencemanager.munki...
No match found on URL: https://www.mendeley.com/download-reference-manager
Failed.

The following recipes failed:
    mendeleyreferencemanager.munki
        Error in local.munki.mendeleyreferencemanager: Processor: URLTextSearcher: Error: No match found on URL: https://www.mendeley.com/download-reference-manager

Nothing downloaded, packaged or imported.

**Comment by joshua-d-miller** [comment]
I have updated the search URL and criteria which has allowed this recipe to resume normal functionally. If you have further issues please be sure to let me know. Thanks for bringing this to my attention.
