### ISSUE TITLE
Error with the zotero recipe 

### ISSUE THREAD

**Issue by ewtillman** [autopkg/joshua-d-miller-recipes#109]
I am not sure whats going on, UrlDownloader string in the download.recipe looks like it should match up fine.
https://www.zotero.org/download/client/dl?channel=release&platform=mac&version=5.0.96.3

Error in com.github.joshua-d-miller.autopkg.munki.zotero: Processor: URLTextSearcher: Error: Command '['/usr/bin/curl', '--compressed', '--location', 'https://www.zotero.org/download/']' returned non-zero exit status 60.

**Comment by joshua-d-miller** [comment]
I have switched the search page to the changeling which has allowed this recipe to resume functionality. If you have any further issues please let me know.

**Comment by ewtillman** [comment]
Hey thanks for looking at this so quickly.
Unfortunantly I am still getting an error, my autopkgr is up to date with your repo.
The following recipes failed:
    com.github.joshua-d-miller.autopkg.munki.zotero
        Error in com.github.joshua-d-miller.autopkg.munki.zotero: Processor: URLTextSearcher: Error: Command '['/usr/bin/curl', '--compressed', '--location', 'https://www.zotero.org/support/changelog']' returned non-zero exit status 60.

**Comment by ewtillman** [comment]
@homebysix   Thanks for verifying it works.
Ran the curl command and no output, ran it on another mac and it worked fine.
Ran the curl command without -s and looks like I have some sort of expired cert issue even though the page loads fine in safari and cert looks good.  I will be all good once I figure out curls cert issue out.
 curl -IL "https://www.zotero.org/support/changelog"
curl: (60) SSL certificate problem: certificate has expired

curl -ILk "https://www.zotero.org/support/changelog"
HTTP/1.1 200 OK
Date: Wed, 08 Dec 2021 17:53:28 GMT
Server: Apache/2.4.48 (Amazon) mod_wsgi/3.5 Python/2.6.9
Set-Cookie: DokuWiki=lcf92p09hd1smq31mee5nlcud0; path=/support/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: DWbc8d5114a0317112aa100ce2b5f2ba65=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/support/; secure; HttpOnly
Set-Cookie: zotero_www_session=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; domain=www.zotero.org
Set-Cookie: zotero_www_session=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; domain=.zotero.org
Set-Cookie: lussumocookieone=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; domain=.forums.zotero.org
Vary: Accept-Encoding
Content-Type: text/html; charset=utf-8
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

**Comment by ewtillman** [comment]
Fixed:  The  DST Root CA X3 Expiration got me, had to edit the /etc/ssl/cert.pem

https://stackoverflow.com/questions/69387175/git-for-windows-ssl-certificate-problem-certificate-has-expired/69396425#69396425
