### ISSUE TITLE
Evernote download failing

### ISSUE THREAD

**Issue by eshirk** [autopkg/joshua-d-miller-recipes#112]
It looks like the download URL may have changed. Currently:
https://cdn1.evernote.com/boron/mac/builds/Evernote-10.31.6-mac-ddl-ga-3237-31284dfc1e.dmg

The download recipe is using:
https:\/\/cdn[\d]\.evernote\.com\/boron\/mac\/builds\/Evernote-[\d.]+-.*[\d]+\.dmg

**Comment by joshua-d-miller** [comment]
It's really fun they keep changing this haha. I will get this resolved.

**Comment by joshua-d-miller** [comment]
This should now be fixed. Give a try and let me know.

**Comment by eshirk** [comment]
Works perfectly--thank you!
