### ISSUE TITLE
Audacity Recipe won't pull past version 3.0.2

### ISSUE THREAD

**Issue by JCSmillie** [autopkg/joshua-d-miller-recipes#113]
Audacity.download doesn't appear to want to grab anything past v3.0.2.  I think its because this is what its looking for as input:
`{'Input': {'asset_regex': 'audacity-macos-[\\d]\\.[\\d]\\.[\\d]\\.dmg',`

All versions after 3.0.3 have "-intel" at the end so for instance "audacity-macos-3.1.3-Intel.dmg" which wouldn't get picked up here.

**Comment by TK5-Tim** [comment]
I just noticed that as well and will look into it and offer a solution in a PR.

**Comment by joshua-d-miller** [comment]
This should be resolved with the latest pull request. Please verify and let me know :)

**Comment by JCSmillie** [comment]
My instance pulled the latest version after I updated my repos.  Thank you!
