### ISSUE TITLE
Enhancement: separate Stellarium Intel/ARM recipes

### ISSUE THREAD

**Issue by eshirk** [autopkg/joshua-d-miller-recipes#115]
There are now separate Intel and ARM downloads for Stellarium. The existing recipe is downloading the ARM version, I believe because it's the first one evaluated. Now that Autopkg supports imports for multiple architectures, it would be great to have both Intel and ARM Stellarium munki recipes.

**Comment by joshua-d-miller** [comment]
This has been updated with pull request #119
