### ISSUE TITLE
AmazonMusic-jdm.download outdated download URL

### ISSUE THREAD

**Issue by opus-nbo** [autopkg/joshua-d-miller-recipes#117]
Looks like the download URL is outdated (downloads version 7.x), noticed it because the version is not compatible with macOS Monterey

Here is a request that gets the latest download URL:

https://qatgqujbd2.execute-api.us-west-2.amazonaws.com/prod/getCurrentVersion

 We only need a way to extract and use it.

**Comment by Daz-wallace** [comment]
Not sure if related but when I use the `installbuilder.sh` from within the Amazon Music installer it errors out with a "The current OS X version is not supported" but a GUI install of the same "Amazon Music Installer" works fine :/ 
Seems to be the same on the installer from the URL above and from the URL in the .download recipe.
I would guess that Amazon have bad code in the installbuilder file. I've no idea how we'd get that to the attention of the right Devs...

**Comment by opus-nbo** [comment]
@joshua-d-miller Can you maybe update the recipe for Amazon Music to get the app from the URL above?

**Comment by joshua-d-miller** [comment]
Download URL tested and updated. Sorry for the long delay!
