### ISSUE TITLE
AdobeAcrobatDCUpdate.munki.recipe flat_pkg_path and also version issue

### ISSUE THREAD

**Issue by rrenstrom** [autopkg/joshua-d-miller-recipes#12]
When overriding the recipe to choose the Classic track release ( "MAJOR_VERSION" = Acrobat2015), it fails with:
Error in local.munki.AdobeAcrobatDCUpdate: Processor: FlatPkgUnpacker: Error: No valid path found as given by 'flat_pkg_path'

since it's looking for a file AcrobatDCUpd*.pkg, but the actual package filename is Acrobat2015Upd1500630121.pkg.  I fixed the recipe by changing flat_pkg_path key to instead reference the file as Acrobat*Upd*.pkg, which will cover both names.

Additionally, there's an issue with extracting the version on the update that was released today (2015.006.30121). It's extracting the version info from                 <string>%RECIPE_CACHE_DIR%/application_payload/Applications/AcroServicesUpdater.app/Contents/Info.plist</string>, but apparently Adobe didn't bump the version of this app in this release, so it's using the old version number (15.006.30119).  Perhaps a work-around would be to use the PackageInfoVersioner processor (https://github.com/facebook/Recipes-for-AutoPkg/tree/master/Shared_Processors) with the Payload.pkg

**Comment by joshua-d-miller** [comment]
So after some digging I found how Adobe gets the version which is sad but it works.  They reference this URL https://armmf.adobe.com/arm-manifests/mac/AcrobatDC/acrobat/current_version.txt which only lists the version.  I have gone ahead and just incorporated this using URLTextSearcher.  I'm sure it will break at some point but it seems to work well.

**Comment by rrenstrom** [comment]
For Classic track version, need to use https://armmf.adobe.com/arm-manifests/mac/Acrobat2015/acrobat/current_version.txt 

Also the Classic track installs in /Applications/Adobe Acrobat 2015/ (rather than /Applications/Adobe Acrobat DC), so the installs path in additional_pkginfo isn't correct for Classic. Likely separate Classic/Continuous track recipes are needed to handle differences.
