### ISSUE TITLE
AdobeCreativeCloudInstallerUniversal pkg path does not match parent recipe

### ISSUE THREAD

**Issue by camguise** [autopkg/joshua-d-miller-recipes#121]
The MunkiImporter task in the [AdobeCreativeCloudInstallerUniversal.munki.recipe](https://github.com/autopkg/joshua-d-miller-recipes/blob/master/Adobe/AdobeCreativeCloudInstallerUniversal.munki.recipe) file has a `pkg_path` specified with the file name hard coded. In [rtrouton's parent recipe](https://github.com/autopkg/rtrouton-recipes/blob/master/AdobeCreativeCloud/AdobeCreativeCloudInstallerUniversal.pkg.recipe) it is possible to change this file path name by specifying input for `VENDOR` and `NAMEWITHOUTSPACES` in the recipe override. I have done this in my override and it means this recipe cannot import the file into Munki because it can't find the file it is expecting. I was going to create a pull request but it is only one line of code that needs modified. I've put the line below for reference so hopefully this will make it a nice quick fix to this recipe. I've confirmed that changing only the one line below does work for me (if I run manually and ignore parent trust).

Line 51 in munki recipe is currently:
`<string>%RECIPE_CACHE_DIR%/AdobeCreativeCloudInstaller-Universal-%version%.pkg</string>`

It should be:
`<string>%RECIPE_CACHE_DIR%/%VENDOR%%NAMEWITHOUTSPACES%-Universal-%version%.pkg</string>`

You may also be best to include the below Input keys/values to your Munki recipe to match the rtrouton parent recipe:
```
<key>VENDOR</key>
<string>Adobe</string>
<key>SOFTWARETITLE</key>
<string>Creative Cloud Installer</string>
<key>NAMEWITHOUTSPACES</key>
<string>CreativeCloudInstaller</string>
```

I'm still a bit green with Git but if you would prefer me to try and create a pull request for this change please let me know.

**Comment by joshua-d-miller** [comment]
I have corrected this and tested. You should be all set!
