### ISSUE TITLE
RStudio download recipe search pattern regex doesn't match on the newest Rstudio download package

### ISSUE THREAD

**Issue by undulat** [autopkg/joshua-d-miller-recipes#122]
RStudio download recipe search pattern regex doesn't match on the newest Rstudio download package

**Comment by joshua-d-miller** [comment]
Sorry for the delayed response. I just checked the RStudio recipe and it appears that it actually does download from the current search pattern. Are you still having issues with this recipe?

**Comment by gahel** [comment]
At the moment it seems to fail with:
    RStudio.munki.recipe
        Error in local.munki.RStudio: Processor: URLDownloader: Error: curl: (6) Could not resolve host: %DOWNLOAD_MIRROR%

**Comment by joshua-d-miller** [comment]
This should now be taken care of with the latest merge for RStudio
