### ISSUE TITLE
No support for Unity Apple Silicon...

### ISSUE THREAD

**Issue by wegotoeleven** [autopkg/joshua-d-miller-recipes#124]
... so I've made a PR! https://github.com/autopkg/joshua-d-miller-recipes/pull/123

**Comment by joshua-d-miller** [comment]
This issue was addressed with the latest pull request

**Comment by eshirk** [comment]
Thank you for this! I'd like to have both versions in my Munki service, so I made a recipe override for each version, but the Munki recipes aren't seeing a difference between the two packages and will only import one. Is there a feasible way around this?
