### ISSUE TITLE
RStudio download recipe 404 error

### ISSUE THREAD

**Issue by vmiller** [autopkg/joshua-d-miller-recipes#131]
The RStudio download recipe is erroring out with a 404 error.  Likely the download URL has changed.  I'll poke at it a bit and see if I can send a pull request with a fix.

**Comment by eshirk** [comment]
Just looked at this and I think the download mirror URL has changed to https://download1.rstudio.org/electron/macos

**Comment by vmiller** [comment]
That's what I found also.  I submitted a pull request with that change.

**Comment by rquigley-aus** [comment]
The search URL has also changed to: https://posit.co/download/rstudio-desktop/

**Comment by joshua-d-miller** [comment]
Should now be addressed with the merged pull request
