### ISSUE TITLE
Unity3D.download doesn't support year based versioning

### ISSUE THREAD

**Issue by andrewvalentine** [autopkg/joshua-d-miller-recipes#149]
At present, running Unity3D.download retrieves the latest version of the 2022 iteration of the app. Can support be implemented for retrieving 2023?

All versions can be accessed via:

https://unity.com/releases/editor/archive

With the 2023 URL being:

https://unity.com/releases/editor/archive#download-archive-2023

The URL for the Apple Silicon version of the latest version of the 2023 pkg still seems to match your existing regex though?

https://download.unity3d.com/download_unity/9dce81d9e7e0/MacEditorInstallerArm64/Unity.pkg

Thanks

**Comment by TonyPaco** [comment]
https://github.com/autopkg/joshua-d-miller-recipes/pull/153

**Comment by joshua-d-miller** [comment]
I believe the Unity recipe was updated and this can now be closed.
