### ISSUE TITLE
Mendeley Reference Manager download recipe failing

### ISSUE THREAD

**Issue by eddiekelley** [autopkg/joshua-d-miller-recipes#156]
We're seeing an error with the [Mendeley Reference Manager for Desktop](https://github.com/autopkg/joshua-d-miller-recipes/blob/master/Mendeley/MendeleyReferenceManager.download.recipe) download recipe, and it seems to be an issue with the regex that's being used to search for the version.

Maybe this is an issue with the triple-digit-decimal in v.**2.100.0** not matching the regex specified on line 37 of that recipe (is it searching for a decimal of length 2 in the minor version?):

`                <string>(?P&lt;Version&gt;\d\.\d{2}\.\d\.dmg)</string>`

**Comment by Steffan-Ravn** [comment]
It's indeed where the problem arrises. I've created a pull request to fix it, but you can easily fix it yourself, either by changing it to 3 digits or, as I proposed in my PR, changing it to accept 1-3 digits:
`<string>(?P&lt;Version&gt;\d\.\d{1,3}\.\d\.dmg)</string>`

**Comment by paul-cossey** [comment]
We've been running a temporary copy of your fix for this issue, @Steffan-Ravn, but it's failed again today.

I've got it working with a couple of changes

- Updated regex `(([A-Za-z0-9]+(\.[A-Za-z0-9]+)+)-x64\.dmg)` - this should capture any version number Mendeley change to. 
```
<key>re_pattern</key>
<string>(([A-Za-z0-9]+(\.[A-Za-z0-9]+)+)-x64\.dmg)</string>
```
- change from `%version%` to `%match%` on the download URL. 
```
<key>url</key>
<string>%DOWNLOAD_PART_URL%-%match%</string>
```

Not sure if you want to amend your PR, or I can knock up a new one? 

Do you have a preference, @joshua-d-miller?

**Comment by joshua-d-miller** [comment]
Closing as this was merged.
