### ISSUE TITLE
Update Zotero Sctipts

### ISSUE THREAD

**Issue by gmarnin** [autopkg/joshua-d-miller-recipes#19]
The postinstall_script and postuninstall_script need to get updated for Office 2016

**Comment by joshua-d-miller** [comment]
So the scripts I have in there check for existence of Office 2011. If I remember correctly most plugins actually install in the user's directory which shouldn't require admin privileges. I know EndNote actually goes into */Library/Application Support/Microsoft/Office365/User\ Content.localized/Startup.localized/Word*. Is this the same case for Zotero?

**Comment by gmarnin** [comment]
Ah, looks like `Zotero.dot` is located in `~/Library/Group Containers/UBF8T346G9.Office/User Content/Startup/Word`. I don't see anything in `/Library`

**Comment by joshua-d-miller** [comment]
So since this is in the user library there might not be a need for scripts since users should be able to write to their library. Please test though and let me know.

**Comment by joshua-d-miller** [comment]
I'm going to close this since I haven't heard anything in a few months.
