### ISSUE TITLE
LogitechOptions.munki Error - No Match Found on URL

### ISSUE THREAD

**Issue by vmgstudio520** [autopkg/joshua-d-miller-recipes#21]
The "LogitechOptions.munki" recipe is reporting an error in AutoPkgr - "No match found on URL: http://support.logitech.com/en_us/software/options".

**Comment by joshua-d-miller** [comment]
Currently working on this. They changed the way their site displays again and I'm looking for a way to get the download again. Sorry for the inconvenience.

**Comment by joshua-d-miller** [comment]
Please sync my latest committed changes and see if it works for you. They finally have a generic URL to download the Options zip file.

**Comment by vmgstudio520** [comment]
Worked! Thank you for fixing!! :)
