### ISSUE TITLE
Dashlane download recipe getting old version

### ISSUE THREAD

**Issue by hfike** [autopkg/joshua-d-miller-recipes#25]
Running this recipe fetches version 4.1.2. Autopkg is running on 10.8.5, however, this should not matter as the user agent specifies 10.9.5. Downloading from the same URL in 10.12 gets 4.6.6. According to their support website ( https://support.dashlane.com/hc/en-us/articles/202625002 ), they now require 10.10 or later. Should the user agent get bumped to at least 10.10?

**Comment by joshua-d-miller** [comment]
Please see latest push as I updated the user agent to 10.10.5

**Comment by hfike** [comment]
Ran a repo-update and still not working, but I noticed my override contained the old user agent info, so I removed that and re-ran the recipe and it pulled the latest version. Thanks!
