### ISSUE TITLE
No match found on URL: https://www.zotero.org/download/

### ISSUE THREAD

**Issue by Gibbun** [autopkg/joshua-d-miller-recipes#32]
I'm seeing the following error when I run the Zotero recipe

    + /usr/local/bin/autopkg run -v --post 
    + io.github.hjuutilainen.VirusTotalAnalyzer/VirusTotalAnalyzer 
    + Zotero.munki

    No match found on URL: https://www.zotero.org/download/

    Failed.

    Processing Zotero.munki...
    URLTextSearcher
    Receipt written to /Users/Shared/AutoPkg/Cache/local.munki.Zotero/receipts/Zotero-receipt-20170710-    134944.plist

    The following recipes failed:
    Zotero.munki
           Error in local.munki.Zotero: Processor: URLTextSearcher: Error: No match found on URL: https://www.zotero.org/download/

**Comment by rustymyers** [comment]
Looks like you'll need to update the recipe to build a download url: https://www.zotero.org/download/client/dl?channel=release&platform=mac&version=5.0.7

**Comment by rustymyers** [comment]
Example for windows side: https://github.com/autopkg/hansen-m-recipes/blob/master/Zotero/Zotero-Win.download.recipe

**Comment by joshua-d-miller** [comment]
I have updated the URL by fetching the version and appending it to their default download link. Give it a shot 👍

**Comment by joshua-d-miller** [comment]
Any updates on whether this is working for you guys?

**Comment by rustymyers** [comment]
Works for us!

**Comment by Gibbun** [comment]
Yes! Thanks!

**Comment by joshua-d-miller** [comment]
Great! Thanks for the feedback guys. I'll go ahead and close this.
