### ISSUE TITLE
LogitechOptions - make Kext pkgs Optional

### ISSUE THREAD

**Issue by blackthroat** [autopkg/joshua-d-miller-recipes#35]
LogitechOptions.munki.recipe

Machine does not recognize that Logitech Options has already been installed, and upon each Managed Software Center update, Logitech Options is added to the Updates tab. "Since not every subpackage will actually be installed, Munki will continually mark the item as not currently installed and offer to install it again and again."

Making `com.Logitech.signedKext.pkg` and `com.Logitech.unsignedKext.pkg` Kext pkgs Optional installs should fix this. Here is what the receipts array should look like:

```
	<array>
		<dict>
			<key>installed_size</key>
			<integer>54732</integer>
			<key>optional</key>
			<false/>
			<key>packageid</key>
			<string>com.logitech.manager.pkg</string>
			<key>version</key>
			<string>6.62</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>359</integer>
			<key>optional</key>
			<true/>
			<key>packageid</key>
			<string>com.Logitech.signedKext.pkg</string>
			<key>version</key>
			<string>1.0.0</string>
		</dict>
		<dict>
			<key>installed_size</key>
			<integer>376</integer>
			<key>optional</key>
			<true/>
			<key>packageid</key>
			<string>com.Logitech.unsignedKext.pkg</string>
			<key>version</key>
			<string>1.0.0</string>
		</dict>
	</array>
```

**Comment by joshua-d-miller** [comment]
Please update your repo of these recipes as I've added the ability to look for installs of the application itself and the preference pane launcher. This should alleviate the package receipts issue.

**Comment by blackthroat** [comment]
Updated. That did the trick, thanks!
