### ISSUE TITLE
Dashlane recipe not downloading new version

### ISSUE THREAD

**Issue by macgurus** [autopkg/joshua-d-miller-recipes#39]
If you go to the /directdownload link it downloads v. 5+ plus via the recipe it seems to be getting served only v. 4+ likely due to the user agent line in the download perhaps. 

$ autopkg run -v Dashlane.munki
Processing Dashlane.munki...
URLDownloader
URLDownloader: Storing new Last-Modified header: Wed, 16 Aug 2017 21:59:36 GMT
URLDownloader: Storing new ETag header: "20376e0d7d323793a21bde39ad695787"
URLDownloader: Downloaded /Library/AutoPkg/Cache/local.munki.Dashlane/downloads/Dashlane.dmg
EndOfCheckPhase
MunkiImporter
MunkiImporter: Item Dashlane.dmg already exists in the munki repo as pkgs/apps/dashlane/Dashlane-4.8.4.dmg.
Receipt written to /Library/AutoPkg/Cache/local.munki.Dashlane/receipts/Dashlane-receipt-20171117-052654.plist

**Comment by joshua-d-miller** [comment]
I have updated the user agent for my recipe however if you have a user agent in your override you will need to remove that to use the new agent. I'll be closing this issue. Sorry it took so long to address.
