### ISSUE TITLE
OBS.munki fails

### ISSUE THREAD

**Issue by rdamienc** [autopkg/joshua-d-miller-recipes#42]
~ % autopkg run -v OBS.munki
Processing OBS.munki...
WARNING: OBS.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
No JSON object could be decoded
Failed.
Receipt written to /Users/damien/Library/AutoPkg/Cache/com.github.joshua-d-miller.autopkg.munki.OBS/receipts/OBS-receipt-20180314-183928.plist

The following recipes failed:
    OBS.munki
        Error in com.github.joshua-d-miller.autopkg.munki.OBS: Processor: GitHubReleasesInfoProvider: Error: No JSON object could be decoded

Nothing downloaded, packaged or imported.

**Comment by macmule** [comment]
@rdamienc check https://github.com/autopkg/joshua-d-miller-recipes/commit/d74125439219964ac0a385fa1de992a2e12e662a

**Comment by joshua-d-miller** [comment]
Looks like I forgot to close this issue as a previous pull request I merged resolved this issue. Sorry!
