### ISSUE TITLE
Dashlane does not download

### ISSUE THREAD

**Issue by beatlemike** [autopkg/joshua-d-miller-recipes#53]
The recipe just creates a broken dmg that appears to be incomplete and cannot be mounted

**Comment by ewtillman** [comment]
Same issue for me, happening on org.croptrust.autopkg.munki.dashlane also

**Comment by joshua-d-miller** [comment]
I merged the pull request but the download still seems to fail. I'm going to do some further investigation into the issue.

**Comment by joshua-d-miller** [comment]
Dashlane should now be fixed. Please check the lastest commits and verify.
