### ISSUE TITLE
RStudio gives error

### ISSUE THREAD

**Issue by Peter-Erik** [autopkg/joshua-d-miller-recipes#55]
Hi. get an error with Autopkg

autopkg run RStudio.munki
Processing RStudio.munki...
Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.

The following recipes failed:
    RStudio.munki
        Error in local.munki.RStudio: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)

Nothing downloaded, packaged or imported.

**Comment by Peter-Erik** [comment]
Thanks

Peter-Erik

**Comment by joshua-d-miller** [comment]
The RStudio download recipe has been fixed. Be sure to remove the download mirror and search pattern in your override.
