### ISSUE TITLE
RStudio recipe still broken

### ISSUE THREAD

**Issue by thevoidboy** [autopkg/joshua-d-miller-recipes#57]
xxxxxx$ autopkg run RStudio.munki
Processing RStudio.munki...
Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.

The following recipes failed:
    RStudio.munki
        Error in local.munki.RStudio: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)

**Comment by notverypc** [comment]
Removing the following from my recipe override resolved the error as it uses the download info from the parent recipe.

```
<key>DOWNLOAD_MIRROR</key>
		<string>http://download1.rstudio.org</string>
		<key>MUNKI_REPO_SUBDIR</key>
		<string>apps/RStudio</string>
		<key>NAME</key>
		<string>RStudio</string>
		<key>SEARCH_PATTERN</key>
		<string>(?P&lt;dmg&gt;RStudio-(?P&lt;version&gt;[0-9.]+)\.dmg)</string>
		<key>SEARCH_URL</key>
		<string>https://www.rstudio.com/products/rstudio/download/</string>
```

**Comment by joshua-d-miller** [comment]
You are correct. Removing the download mirror from an override does resolve the issue as the original download recipe has been fixed.
