### ISSUE TITLE
Stencyl download URL

### ISSUE THREAD

**Issue by P3z** [autopkg/joshua-d-miller-recipes#59]
Hi, it looks like the Stencyl recipe has a new URL of 'http://www.stencyl.com/download/get/dmg/' rather than '.../get/mac/'
I thought Stencyl might be on its way out but they put out some new updates!  Thank you!

**Comment by joshua-d-miller** [comment]
The Stencyl recipe should now be fixed. Make sure you are not specifying the URL in your override.
