### ISSUE TITLE
SMARTNotebook11.download recipe gives "no match found" error

### ISSUE THREAD

**Issue by flammable** [autopkg/joshua-d-miller-recipes#6]
Hello, and thanks for the SMART Notebook recipe!  I really hate their installer/updater, and this makes things much easier on my end (especially as more and more faculty request this software).

I run AutoPkg regularly.  The past few days, this recipe (and the associated .munki one) have been returning a "no match found" error.  I ran the .download recipe in verbose mode:

````
flammable:~ mike$ autopkg run -v SMARTNotebook11.download
Processing SMARTNotebook11.download...
URLTextSearcher
No match found on URL: http://smarttech.com/Support/Browse+Support/Download+Admin+Software
Failed.
Receipt written to /Users/mike/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.smartnotebook11/receipts/SMARTNotebook11-receipt-20150411-224431.plist

The following recipes failed:
    SMARTNotebook11.download
        Error in com.github.joshua-d-miller.download.smartnotebook11: Processor: URLTextSearcher: Error: No match found on URL: http://smarttech.com/Support/Browse+Support/Download+Admin+Software

Nothing downloaded, packaged or imported.
````

I'm guessing they changed their website, which broke the recipe.  Would you be willing to take a look, when you have a chance?  Thank you so much!

Mike

**Comment by joshua-d-miller** [comment]
Hello there,

First of all thank you for bringing this issue to my attention.  Also you were correct that they changed their URL slightly.  I have gone ahead and made the changes and committed them.  In testing it seemed to download just fine on my end however I'd like for you to sync the repo and test it before I close the issue.  Let me know how it works for you.

Thanks again!

**Comment by flammable** [comment]
It works great!  Thank you!

**Comment by flammable** [comment]
Sorry to bother you again, but am seeing the same failures again:

```
flammable:~ mike$ autopkg run -v SMARTNotebook11.download
Processing SMARTNotebook11.download...
URLTextSearcher
No match found on URL: http://smarttech.com/Support/Browse+Support/Download+Admin+Software
Failed.
Receipt written to /Users/mike/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.smartnotebook11/receipts/SMARTNotebook11-receipt-20150426-203353.plist

The following recipes failed:
    SMARTNotebook11.download
        Error in com.github.joshua-d-miller.download.smartnotebook11: Processor: URLTextSearcher: Error: No match found on URL: http://smarttech.com/Support/Browse+Support/Download+Admin+Software

Nothing downloaded, packaged or imported.
```

Looks like they changed their website again, ugh.  If you'd prefer that I open a new issue instead, I can do that!

Thank you!

**Comment by joshua-d-miller** [comment]
Its ok to reopen this however it looks like the link may have been removed completely.  I'm going to check with SMART and see if they are still updating version 11 and if not this recipe will probably be discontinued.

**Comment by joshua-d-miller** [comment]
Hello.  After speaking with SMART they have indicated that this version will no longer be offered from them and it will no longer receive updates.  Our university is currently pursuing a 2015 license so once we have that I will make a SMART NoteBook 2015 license.  Sorry about that!

**Comment by flammable** [comment]
Thanks again, I appreciate the work you've done for this!
