### ISSUE TITLE
Unity3D.download changed to .dmg

### ISSUE THREAD

**Issue by dcoobs** [autopkg/joshua-d-miller-recipes#62]
Looks like the Unity 3D download recipe [now outputs a .dmg instead of a .pkg](https://github.com/autopkg/hansen-m-recipes/commit/b55dcd5c352f164243dc998e65c13fe88023bbf9). The munki recipe should be updated to either use the dmg or switch to using [the new pkg recipe created](https://github.com/autopkg/dataJAR-recipes/blob/master/Unity3D/Unity3D.pkg.recipe).

**Comment by joshua-d-miller** [comment]
Actually, the download recipe was changed in the other repo to the Unity Hub application which is different than Unity 3D Editor. I have gone ahead and created a download recipe that downloads the 3D Editor as before. Please update your version of my repo :)
