### ISSUE TITLE
DYMOLabel.download issue

### ISSUE THREAD

**Issue by eshirk** [autopkg/joshua-d-miller-recipes#67]
URLTextSearcher is failing to find a match on http://www.dymo.com/en-US/online-support/dymo-user-guides. wondering if it's the 'feedback' popup that's interfering?

**Comment by Daz-wallace** [comment]
Possible fix in a pull request - #69

**Comment by joshua-d-miller** [comment]
This has been addressed with a pull request. Tested this morning and the download worked.
