### ISSUE TITLE
MacTex 2015 version is still 1.0

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/joshua-d-miller-recipes#7]
AutoPKG says hello MacTex 2015.
Unfortunately it is imported to munki as version 1.0 (same as MacTex 2014).

I am not sure if this is relevant issue for you since there is no repackage recipe but I'll leave this issue here.

**Comment by joshua-d-miller** [comment]
MichalMMac,

Thank you for this update.  I have updated the MacTeX recipe and it should function properly now since their packaging seems to be odd.  Since there is only one update a year it seems I have reflected that in the recipe.  Please try and let me know if this works for you.

Thanks!

**Comment by MichalMMac** [comment]
Looks good. Thank you :+1:
