### ISSUE TITLE
Unity3D.download.recipe issue

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/joshua-d-miller-recipes#71]
Running Unity3D.download.recipe in AutoPKG returns the error:

URLTextSearcher: Error: No match found on URL: https://unity3d.com/unity/whats-new

Pull request incoming

**Comment by eshirk** [comment]
Looks like the vendor reverted to the original URL, and the Unity3D.download recipe is (for now) working as-is.

**Comment by joshua-d-miller** [comment]
Resolved by pull request.
