### ISSUE TITLE
Unity3D.download.recipe issue

### ISSUE THREAD

**Issue by macmule** [autopkg/joshua-d-miller-recipes#73]
Looks like they have moved this now to required UnityHub, going to https://unity3d.com/unity/whats-new will send you to links which take you to: https://unity3d.com/get-unity/update

![Screenshot 2019-10-24 14 30 44](https://user-images.githubusercontent.com/2464974/67490346-fb06bd80-f66a-11e9-9c7f-b3fa01bcefbc.png)

The additional downloads has a Torrent.. maybe that could be used?

**Comment by joshua-d-miller** [comment]
Please try the latest update as the URL has been updated.

**Comment by apizz** [comment]
@joshua-d-miller Looks like the URL is different again!   This is the current link: https://download.unity3d.com/download_unity/b1a7e1fb4fa5/MacEditorInstaller/Unity.pkg

**Comment by apizz** [comment]
Thinking this might be the way to go regex-wise?:
`https:\/\/[a-z0-9]+\.unity3d\.com\/.*\/MacEditorInstaller\/Unity\.pkg`

Accepts any subdomain of unity3d.com and any subfolders up til MacEditorInstaller with Unity inside.

**Comment by joshua-d-miller** [comment]
The latest update to the repo addresses this issue. Thank you @apizz and sorry it took so long to update this.
