### ISSUE TITLE
Deprecate OBS recipes

### ISSUE THREAD

**Issue by nstrauss** [autopkg/joshua-d-miller-recipes#78]
Going through https://gist.github.com/homebysix/7b2800c1d7494649a14a0f18cb62926c and found old OBS recipes last updated two years ago. Download recipe uses GitHubReleasesInfoProvider which is a release or two behind compared to OBS direct download. 

My recipes (https://github.com/autopkg/nstrauss-recipes/tree/master/OBS) are updated to use the direct download from https://obsproject.com/download My guess is you don't have a need/want to maintain these anymore 🤷‍♂ Requesting they be deprecated/removed from repo to avoid duplicate recipes.

**Comment by joshua-d-miller** [comment]
Hello @nstrauss. If you have updated the OBS Recipes I will go ahead and remove mine as clearly they are no longer needed.

Thanks!
