### ISSUE TITLE
Stencyl recipe fails at Versioner

### ISSUE THREAD

**Issue by ABrdfd** [autopkg/joshua-d-miller-recipes#79]
The Stencyl recipe has been failing for me.  The dmg seems to mount and successfully goes through CodeSignatureVerifier, but then fails at Versioner when locating the Info.plist
Not sure what's wrong with the path - looks OK from my vantage.  

Here is my error log:

CodeSignatureVerifier
{'Input': {'input_path': '/Users/admin/Library/AutoPkg/Cache/local.munki.Stencyl/downloads/Stencyl.dmg/Stencyl-*/Stencyl.app',
           'requirement': 'identifier "com.stencyl.Stencyl" and anchor apple '
                          'generic and certificate '
                          '1[field.1.2.840.113635.100.6.2.6] /* exists */ and '
                          'certificate leaf[field.1.2.840.113635.100.6.1.13] '
                          '/* exists */ and certificate leaf[subject.OU] = '
                          'XQ3UWKJ48P'}}
CodeSignatureVerifier: hdiutil imageinfo error nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
 with image /Users/admin/Library/AutoPkg/Cache/local.munki.Stencyl/downloads/Stencyl.dmg.
CodeSignatureVerifier: Mounted disk image /Users/admin/Library/AutoPkg/Cache/local.munki.Stencyl/downloads/Stencyl.dmg
CodeSignatureVerifier: Using path '/private/tmp/dmg.GHYbMn/Stencyl-4.0.2-mac/Stencyl.app' matched from globbed '/private/tmp/dmg.GHYbMn/Stencyl-*/Stencyl.app'.
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.GHYbMn/Stencyl-4.0.2-mac/Stencyl.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.GHYbMn/Stencyl-4.0.2-mac/Stencyl.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.GHYbMn/Stencyl-4.0.2-mac/Stencyl.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
{'Output': {}}
Versioner
{'Input': {'input_plist_path': '/Users/admin/Library/AutoPkg/Cache/local.munki.Stencyl/downloads/Stencyl.dmg/Stencyl-*/Stencyl.app/Contents/Info.plist',
           'plist_version_key': 'CFBundleVersion'}}
Versioner: hdiutil imageinfo error nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
nx_kernel_mount:1473: : checkpoint search: largest xid 5, best xid 5 @ 9
 with image /Users/admin/Library/AutoPkg/Cache/local.munki.Stencyl/downloads/Stencyl.dmg.
Versioner: Mounted disk image /Users/admin/Library/AutoPkg/Cache/local.munki.Stencyl/downloads/Stencyl.dmg
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/Versioner.py", line 66, in main
    f"File '{input_plist_path}' does not exist or could not be read."
autopkglib.ProcessorError: File '/private/tmp/dmg.vYhrO7/Stencyl-*/Stencyl.app/Contents/Info.plist' does not exist or could not be read.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
File '/private/tmp/dmg.vYhrO7/Stencyl-*/Stencyl.app/Contents/Info.plist' does not exist or could not be read.
Failed.

**Comment by joshua-d-miller** [comment]
Hi There. I have pushed an update that has resolved the Stencyl issues.
