### ISSUE TITLE
NVivo version 11

### ISSUE THREAD

**Issue by flammable** [autopkg/joshua-d-miller-recipes#8]
Thanks for the NVivo recipe!  We just had someone request NVivo version 11, which can be found here:

http://www.qsrinternational.com/support/downloads

Would it be possible to update the recipe for the new version?  Thanks!

Mike

**Comment by joshua-d-miller** [comment]
Latest Update to my repo now has an NVivo 10 recipe and an NVivo 11 recipe.  They will import the same but you can change that in an override.

**Comment by flammable** [comment]
Thanks for this!
