### ISSUE TITLE
Dymo Label recipe fails to download

### ISSUE THREAD

**Issue by micmil** [autopkg/joshua-d-miller-recipes#81]
Error message is "No match found on URL: http://www.dymo.com/en-US/online-support/dymo-user-guides". Dymo appears to be redirecting to a CDN(?) @ https://atropos.newellco.com/. 

Full link to the latest file is https://atropos.newellco.com/filestore/getLink.php?HASH=66a88fef1ad8622738e0e9ab66c2db86&TEMP=1 (not sure how long this will be valid)

**Comment by joshua-d-miller** [comment]
Hi There! I just tested this recipe and it appears that the download has been restored and there does appear to be any need to use the CDN.
