### ISSUE TITLE
NVivo Download issue - URLTextSearcher fails

### ISSUE THREAD

**Issue by stefanj135** [autopkg/joshua-d-miller-recipes#84]
Hi, just reporting this one. 

URLTextSearcher
{'Input': {'re_pattern': u'(?P<url>http(s)?\\://download\\.qsrinternational\\.com/Software/NVivo12forMac/NVivo( [0-9]{2})?\\.dmg)',
           'url': u'http://qsrinternational.com/nvivo/support-overview/downloads'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
No match found on URL: http://qsrinternational.com/nvivo/support-overview/downloads

**Comment by joshua-d-miller** [comment]
I have created a download and munki recipe that will download the latest 20 versions for macOS. The 11 and 10 versions also still download and I can create another recipe for 12 if possible.
