### ISSUE TITLE
DYMOLabel.download URLTextSearcher fails

### ISSUE THREAD

**Issue by neilmartin83** [autopkg/joshua-d-miller-recipes#85]
Hi Josh,

It looks like DYMO have put the page this recipe is scraping at http://www.dymo.com/en-US/online-support/dymo-user-guides behind some kind of javascript based capcha wall, so only browsers running JS can access.

I tried to curl it down with a user agent simulating Chrome but it didn't make any difference.

**Comment by Daz-wallace** [comment]
Hi folks, 

Looks like the download recipe (https://github.com/autopkg/joshua-d-miller-recipes/blob/master/DYMO/DYMOLabel.download.recipe) was updated a few days ago but we're still seeing the above issue. 

I'm not sure if there's an option here or if a workaround has been figured out?

**Comment by lashomb** [comment]
Seeing the same, with the captcha. Tried several approaches, requests, urllib, curl and bs4, but none worked.

**Comment by joshua-d-miller** [comment]
Hello all,

I'm still working on this and it appears that DYMO has placed their downloads behind CloudFlare Captcha so we will need a way to deal with that via python or as referenced above the CloudScraper project. Still working on it. Thanks!

**Comment by Daz-wallace** [comment]
Hi @joshua-d-miller 

Sorry to pester but how are you getting on? I'm not sure what we can do but can we help in anyway?

Thanks again

**Comment by joshua-d-miller** [comment]
Hi @Daz-wallace,

I have contacted DYMO and they basically are of no help.  I think we are going to have to construct some kind of helper to open a a website that is behind cloudflare. I'm exploring options but apologize for the issue.

Thanks!

**Comment by Daz-wallace** [comment]
Hey @joshua-d-miller 

No worries at all, and thanks for taking the time to dig in further 😊

**Comment by joshua-d-miller** [comment]
Hello everyone,

Thanks to DYMO, they have provided direct download links for both Windows and macOS. I have gone ahead and updated the macOS version and the recipe is now functioning properly. I am going to go ahead and post both links in this issue for reference.

Windows: https://download.dymo.com/dymo/oftware/DCDSetup.exe
macOS: https://download.dymo.com/dymo/Software/DLS8Setup.dmg

Thank you for your patience!
