### ISSUE TITLE
Stellarium download

### ISSUE THREAD

**Issue by eshirk** [autopkg/joshua-d-miller-recipes#86]
Looks like the Stellarium download is now a .zip file:

https://github.com/Stellarium/stellarium/releases/download/v0.20.2/Stellarium-0.20.2.zip

**Comment by joshua-d-miller** [comment]
Hello there,

This has been addressed and should now function as it did before they decided to switch to a zip. Should you have any further issues please let me know.

Thanks!

**Comment by eshirk** [comment]
Fabulous--thank you!
