### ISSUE TITLE
TNEF's Enough Not lastest version

### ISSUE THREAD

**Issue by cristianmaida** [autopkg/joshua-d-miller-recipes#89]
The recipe download the version 3.2.1, the latest version is the 3.8

**Comment by joshua-d-miller** [comment]
Hello @cristianmaida, I'm not sure what software you are referring to. Can you provide the software you are referring to?

**Comment by cristianmaida** [comment]
Sorry, TNEFsEnough.
http://www.joshjacob.com/mac-development/tnef.php

**Comment by joshua-d-miller** [comment]
Hello there,

I'm curious if maybe you have a URL in your override as I just ran the recipe and it appears to download version 3.8. Let me know what your override looks like.

Thanks!

**Comment by cristianmaida** [comment]
Hello.
I simply run the recipe with autopkg:
autopkg run TNEFsEnough.munki.recipe

And the download report version 3.2.1:
The following new items were imported into Munki:
    Name         Version  Catalogs  Pkginfo Path                       Pkg Repo Path                    Icon Repo Path  
    ----         -------  --------  ------------                       -------------                    --------------  
    tnefsenough  3.2.1    testing   utilities/tnefsenough-3.2.1.plist  utilities/tnefsenough-3.2.1.dmg

**Comment by joshua-d-miller** [comment]
Hello @cristianmaida,

Can you post your Recipe Override? I'm thinking that there is something in the override that is preventing you from getting the latest version. I actually updated this recipe as well to allow CodeSignatureVerification.

Thanks!

**Comment by joshua-d-miller** [comment]
Hello @cristianmaida,

Is this still an issue for you?

Thanks!

**Comment by joshua-d-miller** [comment]
Hello,

I've not heard whether this is still an issue. If you'd like you can reopen the request however I have been unable to replicate the issue. I would suggest verifying your recipe override and possibly regenerating it.

Thanks!
