### ISSUE TITLE
Jabra Direct's latest package has the wrong version number baked into it

### ISSUE THREAD

**Issue by Prodeguerriero** [autopkg/joshua-d-miller-recipes#91]
This is more of an FYI, as the issue doesn't seem to be with the recipe itself.

The latest Jabra Direct package is listed as `4.14.15119` on their website, but once downloaded it is listed as `4.0.0`, which is then recognized by Munki as an older version compared to the previous one (`4.0.6820`).

I opened a support ticket with them, but I doubt it will yield any results in the short term.

**Comment by joshua-d-miller** [comment]
Thank you for this information. It sounds like we will need to go based off an installs array instead of the pkg receipt. I'll get to work on this.

**Comment by joshua-d-miller** [comment]
Thank you for your patience and for letting me know. I have updated the recipe and tested which now imports into munki and sets the version to the version you have specified. If you have further issues please let me know 👍
