### ISSUE TITLE
OBS.munki improvements

### ISSUE THREAD

**Issue by gregneagle** [autopkg/joshua-d-miller-recipes#96]
The virtual camera feature requires a plugin to be installed to a location that requires admin authorization. If a non-admin user clicks "Start Virtual Camera" for the first time, they are presented with a prompt for admin credentials.

You can avoid this by adding these pre and postinstall scripts to the pkginfo in a recipe override:

```xml
    <key>postinstall_script</key>
    <string>#!/bin/sh

# copy virtual camera plug-in to its needed location to avoid an admin
# credentials prompt when starting the virtual camera for the first time
/bin/cp -R /Applications/OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin /Library/CoreMediaIO/Plug-Ins/DAL/
			</string>
    <key>postuninstall_script</key>
    <string>#!/bin/sh

# remove virtual camera plug-in
/bin/rm -r /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin
			</string>
```

Would be nice to have these in the pkginfo in the recipe itself, but anyone with an existing override would probably need to adjust their override anyway.

There's a more complex fix using PkginfoMerger to explicitly add these scripts to the generated pkginfo, but I'm not motivated enough to make the effort.

Do with this what you will!

**Comment by joshua-d-miller** [comment]
This seems logical to add to the OBS Munki recipe. I'm going to go ahead and add it but as you indicated, users will need to update their overrides to include the new scripts.

**Comment by joshua-d-miller** [comment]
These changes have been applied to the recipe.
